apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: reflex-tls
  namespace: reflex
spec:
  secretName: reflex-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - reflex.demo.managoat.com
